# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_labels', models.TextField(max_length=2000)),
                ('advice_text', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=250)),
                ('question_text', models.TextField(max_length=3000)),
                ('extra_fields', models.TextField(max_length=3000)),
            ],
        ),
    ]
