# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=250)),
                ('answer_label', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='extra_fields',
            new_name='description',
        ),
        migrations.AddField(
            model_name='question',
            name='options_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='q_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recsystem.Question'),
        ),
    ]
