# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recsystem', '0002_auto_20171116_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recsystem.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recsystem.Question')),
            ],
        ),
    ]
