# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recsystem', '0004_followup_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='answser',
            new_name='answer',
        ),
    ]
