# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recsystem', '0005_auto_20171128_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='q_id',
            new_name='question',
        ),
    ]
