# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recsystem', '0006_auto_20171204_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='time_stamp',
            field=models.TextField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
