# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recsystem', '0007_advice_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recsystem.Answer'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='time_stamp',
            field=models.TextField(default=django.utils.timezone.now, max_length=2000),
        ),
    ]
