# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsystem', '0008_auto_20180321_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advice',
            old_name='answer_labels',
            new_name='advice_label',
        ),
        migrations.RemoveField(
            model_name='advice',
            name='answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='advices',
            field=models.ManyToManyField(to='recsystem.Advice'),
        ),
    ]
