# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsystem', '0012_question_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='min',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
