# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsystem', '0013_auto_20180425_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='step',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
